In [ ]:
import numpy as np
d1=np.genfromtxt("/content/testmarks1.csv",delimiter=",")
print(d1)
EDS=d1[:,1]
print(type(EDS)) 
print(max(EDS))

[[   nan    nan    nan    nan    nan]
 [801.    43.05  27.79  28.7   27.79]
 [802.    43.47  28.52  28.98  27.89]
 [803.    42.24  28.16  28.16  25.63]
 [804.    39.24  26.16  26.16  26.16]
 [805.    40.9   26.03  27.27  25.65]
 [806.    39.47  26.31  26.31  25.21]
 [807.    41.68  25.63  27.79  25.46]
 [808.    42.19  27.61  28.13  26.21]
 [809.    44.75  28.35  29.83  28.21]
 [810.    46.95  28.88  31.3   28.53]]
<class 'numpy.ndarray'>
nan


In [ ]:
import numpy as np
d2=np.genfromtxt("/content/testmarks2.csv",delimiter=",")
print(d2)
EDS=d1[:,1]
print(type(EDS))
print(max(EDS))

[[   nan    nan    nan    nan    nan]
 [801.    28.48  34.18  30.56  22.23]
 [802.    28.1   33.72  30.68  22.82]
 [803.    26.16  31.39  28.2   22.53]
 [804.    26.16  31.39  28.78  20.93]
 [805.    26.1   31.32  28.22  20.82]
 [806.    25.45  30.54  27.73  21.05]
 [807.    26.16  31.39  28.01  20.51]
 [808.    27.44  32.93  28.83  22.08]
 [809.    28.63  34.35  31.03  22.68]
 [810.    30.35  36.42  31.38  23.1 ]]
<class 'numpy.ndarray'>
nan


In [ ]:
import numpy as np
d1=np.genfromtxt("/content/testmarks1.csv",delimiter=",")
print(d1)
EDS=d1[1:,1]
print(type(EDS))
print(max(EDS))

[[   nan    nan    nan    nan    nan]
 [801.    43.05  27.79  28.7   27.79]
 [802.    43.47  28.52  28.98  27.89]
 [803.    42.24  28.16  28.16  25.63]
 [804.    39.24  26.16  26.16  26.16]
 [805.    40.9   26.03  27.27  25.65]
 [806.    39.47  26.31  26.31  25.21]
 [807.    41.68  25.63  27.79  25.46]
 [808.    42.19  27.61  28.13  26.21]
 [809.    44.75  28.35  29.83  28.21]
 [810.    46.95  28.88  31.3   28.53]]
<class 'numpy.ndarray'>
46.95


In [ ]:
import numpy as np
d1=np.genfromtxt("/content/testmarks2.csv",delimiter=",")
print(d2)
EDS=d1[1:,1]
print(type(EDS))
print(max(EDS))

[[   nan    nan    nan    nan    nan]
 [801.    28.48  34.18  30.56  22.23]
 [802.    28.1   33.72  30.68  22.82]
 [803.    26.16  31.39  28.2   22.53]
 [804.    26.16  31.39  28.78  20.93]
 [805.    26.1   31.32  28.22  20.82]
 [806.    25.45  30.54  27.73  21.05]
 [807.    26.16  31.39  28.01  20.51]
 [808.    27.44  32.93  28.83  22.08]
 [809.    28.63  34.35  31.03  22.68]
 [810.    30.35  36.42  31.38  23.1 ]]
<class 'numpy.ndarray'>
30.35


In [ ]:
d1=np.genfromtxt("/content/testmarks1.csv",delimiter=",")
print(d1)
EDS=d1[1:,1]
print(type(EDS))
print(max(EDS))
np.count_nonzero(EDS>40)

[[   nan    nan    nan    nan    nan]
 [801.    43.05  27.79  28.7   27.79]
 [802.    43.47  28.52  28.98  27.89]
 [803.    42.24  28.16  28.16  25.63]
 [804.    39.24  26.16  26.16  26.16]
 [805.    40.9   26.03  27.27  25.65]
 [806.    39.47  26.31  26.31  25.21]
 [807.    41.68  25.63  27.79  25.46]
 [808.    42.19  27.61  28.13  26.21]
 [809.    44.75  28.35  29.83  28.21]
 [810.    46.95  28.88  31.3   28.53]]
<class 'numpy.ndarray'>
46.95


8

In [ ]:
d1=np.genfromtxt("/content/testmarks2.csv",delimiter=",")
print(d2)
EDS=d1[1:,1]
print(type(EDS))
print(max(EDS))
np.count_nonzero(EDS>40)

[[   nan    nan    nan    nan    nan]
 [801.    28.48  34.18  30.56  22.23]
 [802.    28.1   33.72  30.68  22.82]
 [803.    26.16  31.39  28.2   22.53]
 [804.    26.16  31.39  28.78  20.93]
 [805.    26.1   31.32  28.22  20.82]
 [806.    25.45  30.54  27.73  21.05]
 [807.    26.16  31.39  28.01  20.51]
 [808.    27.44  32.93  28.83  22.08]
 [809.    28.63  34.35  31.03  22.68]
 [810.    30.35  36.42  31.38  23.1 ]]
<class 'numpy.ndarray'>
30.35


0

In [ ]:
#Addition
result=d1+d2
print("\nUsing Operator:\n",result)
resultarray=np.add(d1,d2)
print("\nUsing Numpy Function:\n",result)



Using Operator:
 [[    nan     nan     nan     nan     nan]
 [1602.     56.96   68.36   61.12   44.46]
 [1604.     56.2    67.44   61.36   45.64]
 [1606.     52.32   62.78   56.4    45.06]
 [1608.     52.32   62.78   57.56   41.86]
 [1610.     52.2    62.64   56.44   41.64]
 [1612.     50.9    61.08   55.46   42.1 ]
 [1614.     52.32   62.78   56.02   41.02]
 [1616.     54.88   65.86   57.66   44.16]
 [1618.     57.26   68.7    62.06   45.36]
 [1620.     60.7    72.84   62.76   46.2 ]]

Using Numpy Function:
 [[    nan     nan     nan     nan     nan]
 [1602.     56.96   68.36   61.12   44.46]
 [1604.     56.2    67.44   61.36   45.64]
 [1606.     52.32   62.78   56.4    45.06]
 [1608.     52.32   62.78   57.56   41.86]
 [1610.     52.2    62.64   56.44   41.64]
 [1612.     50.9    61.08   55.46   42.1 ]
 [1614.     52.32   62.78   56.02   41.02]
 [1616.     54.88   65.86   57.66   44.16]
 [1618.     57.26   68.7    62.06   45.36]
 [1620.     60.7    72.84   62.76   46.2 ]]


In [ ]:
#Subtraction
resul=d1-d2
print("\nUsing Operator:\n",resul)
resultarray=np.subtract(d1,d2)
print("\nUsing Numpy Function:\n",result)


Using Operator:
 [[nan nan nan nan nan]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]

Using Numpy Function:
 [[    nan     nan     nan     nan     nan]
 [1602.     56.96   68.36   61.12   44.46]
 [1604.     56.2    67.44   61.36   45.64]
 [1606.     52.32   62.78   56.4    45.06]
 [1608.     52.32   62.78   57.56   41.86]
 [1610.     52.2    62.64   56.44   41.64]
 [1612.     50.9    61.08   55.46   42.1 ]
 [1614.     52.32   62.78   56.02   41.02]
 [1616.     54.88   65.86   57.66   44.16]
 [1618.     57.26   68.7    62.06   45.36]
 [1620.     60.7    72.84   62.76   46.2 ]]


In [ ]:
#Multiplication
resultarray=d1*d2
print("\nUsing Operator:\n",result)
resultarray=np.multiply(d1,d2)
print("\nUsing Numpy Function:\n",result)


Using Operator:
 [[    nan     nan     nan     nan     nan]
 [1602.     56.96   68.36   61.12   44.46]
 [1604.     56.2    67.44   61.36   45.64]
 [1606.     52.32   62.78   56.4    45.06]
 [1608.     52.32   62.78   57.56   41.86]
 [1610.     52.2    62.64   56.44   41.64]
 [1612.     50.9    61.08   55.46   42.1 ]
 [1614.     52.32   62.78   56.02   41.02]
 [1616.     54.88   65.86   57.66   44.16]
 [1618.     57.26   68.7    62.06   45.36]
 [1620.     60.7    72.84   62.76   46.2 ]]

Using Numpy Function:
 [[    nan     nan     nan     nan     nan]
 [1602.     56.96   68.36   61.12   44.46]
 [1604.     56.2    67.44   61.36   45.64]
 [1606.     52.32   62.78   56.4    45.06]
 [1608.     52.32   62.78   57.56   41.86]
 [1610.     52.2    62.64   56.44   41.64]
 [1612.     50.9    61.08   55.46   42.1 ]
 [1614.     52.32   62.78   56.02   41.02]
 [1616.     54.88   65.86   57.66   44.16]
 [1618.     57.26   68.7    62.06   45.36]
 [1620.     60.7    72.84   62.76   46.2 ]]


In [ ]:
#Division
resultarry=d1/d2
print("\nUsing Operator:\n",result)
resultarray=np.divide(d1,d2)
print("\nUsing Numpy Function:\n",result)


Using Operator:
 [[    nan     nan     nan     nan     nan]
 [1602.     56.96   68.36   61.12   44.46]
 [1604.     56.2    67.44   61.36   45.64]
 [1606.     52.32   62.78   56.4    45.06]
 [1608.     52.32   62.78   57.56   41.86]
 [1610.     52.2    62.64   56.44   41.64]
 [1612.     50.9    61.08   55.46   42.1 ]
 [1614.     52.32   62.78   56.02   41.02]
 [1616.     54.88   65.86   57.66   44.16]
 [1618.     57.26   68.7    62.06   45.36]
 [1620.     60.7    72.84   62.76   46.2 ]]

Using Numpy Function:
 [[    nan     nan     nan     nan     nan]
 [1602.     56.96   68.36   61.12   44.46]
 [1604.     56.2    67.44   61.36   45.64]
 [1606.     52.32   62.78   56.4    45.06]
 [1608.     52.32   62.78   57.56   41.86]
 [1610.     52.2    62.64   56.44   41.64]
 [1612.     50.9    61.08   55.46   42.1 ]
 [1614.     52.32   62.78   56.02   41.02]
 [1616.     54.88   65.86   57.66   44.16]
 [1618.     57.26   68.7    62.06   45.36]
 [1620.     60.7    72.84   62.76   46.2 ]]


In [ ]:
#MOD
resultarry=d1%d2
print("\nUsing Operator:\n",result)
resultarray=np.mod(d1,d2)
print("\nUsing Numpy Function:\n",result)


Using Operator:
 [[    nan     nan     nan     nan     nan]
 [1602.     56.96   68.36   61.12   44.46]
 [1604.     56.2    67.44   61.36   45.64]
 [1606.     52.32   62.78   56.4    45.06]
 [1608.     52.32   62.78   57.56   41.86]
 [1610.     52.2    62.64   56.44   41.64]
 [1612.     50.9    61.08   55.46   42.1 ]
 [1614.     52.32   62.78   56.02   41.02]
 [1616.     54.88   65.86   57.66   44.16]
 [1618.     57.26   68.7    62.06   45.36]
 [1620.     60.7    72.84   62.76   46.2 ]]

Using Numpy Function:
 [[    nan     nan     nan     nan     nan]
 [1602.     56.96   68.36   61.12   44.46]
 [1604.     56.2    67.44   61.36   45.64]
 [1606.     52.32   62.78   56.4    45.06]
 [1608.     52.32   62.78   57.56   41.86]
 [1610.     52.2    62.64   56.44   41.64]
 [1612.     50.9    61.08   55.46   42.1 ]
 [1614.     52.32   62.78   56.02   41.02]
 [1616.     54.88   65.86   57.66   44.16]
 [1618.     57.26   68.7    62.06   45.36]
 [1620.     60.7    72.84   62.76   46.2 ]]


In [1]:
#Dot Product
resultarray=np.dot(d1,d2)
print("",resultarray)

NameError: ignored

In [ ]:
#Transpose
resultarray=np.transpose(d1)
print(resultarray)

[[   nan 801.   802.   803.   804.   805.   806.   807.   808.   809.
  810.  ]
 [   nan  28.48  28.1   26.16  26.16  26.1   25.45  26.16  27.44  28.63
   30.35]
 [   nan  34.18  33.72  31.39  31.39  31.32  30.54  31.39  32.93  34.35
   36.42]
 [   nan  30.56  30.68  28.2   28.78  28.22  27.73  28.01  28.83  31.03
   31.38]
 [   nan  22.23  22.82  22.53  20.93  20.82  21.05  20.51  22.08  22.68
   23.1 ]]


In [ ]:
#Mean
resultd=d1+d2/2

print("\nUsing Operator:\n",resultd)
resultd=np.add(d1,d2)
print("\nUsing NumpyFunction:\n",resultd)


Using Operator:
 [[     nan      nan      nan      nan      nan]
 [1201.5     42.72    51.27    45.84    33.345]
 [1203.      42.15    50.58    46.02    34.23 ]
 [1204.5     39.24    47.085   42.3     33.795]
 [1206.      39.24    47.085   43.17    31.395]
 [1207.5     39.15    46.98    42.33    31.23 ]
 [1209.      38.175   45.81    41.595   31.575]
 [1210.5     39.24    47.085   42.015   30.765]
 [1212.      41.16    49.395   43.245   33.12 ]
 [1213.5     42.945   51.525   46.545   34.02 ]
 [1215.      45.525   54.63    47.07    34.65 ]]

Using NumpyFunction:
 [[    nan     nan     nan     nan     nan]
 [1602.     56.96   68.36   61.12   44.46]
 [1604.     56.2    67.44   61.36   45.64]
 [1606.     52.32   62.78   56.4    45.06]
 [1608.     52.32   62.78   57.56   41.86]
 [1610.     52.2    62.64   56.44   41.64]
 [1612.     50.9    61.08   55.46   42.1 ]
 [1614.     52.32   62.78   56.02   41.02]
 [1616.     54.88   65.86   57.66   44.16]
 [1618.     57.26   68.7    62.06   45.36]


In [ ]:
#Horizontal Stacking
resultarray=np.hstack((d1,d2))
resultarray

array([[   nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    nan],
       [801.  ,  28.48,  34.18,  30.56,  22.23, 801.  ,  28.48,  34.18,
         30.56,  22.23],
       [802.  ,  28.1 ,  33.72,  30.68,  22.82, 802.  ,  28.1 ,  33.72,
         30.68,  22.82],
       [803.  ,  26.16,  31.39,  28.2 ,  22.53, 803.  ,  26.16,  31.39,
         28.2 ,  22.53],
       [804.  ,  26.16,  31.39,  28.78,  20.93, 804.  ,  26.16,  31.39,
         28.78,  20.93],
       [805.  ,  26.1 ,  31.32,  28.22,  20.82, 805.  ,  26.1 ,  31.32,
         28.22,  20.82],
       [806.  ,  25.45,  30.54,  27.73,  21.05, 806.  ,  25.45,  30.54,
         27.73,  21.05],
       [807.  ,  26.16,  31.39,  28.01,  20.51, 807.  ,  26.16,  31.39,
         28.01,  20.51],
       [808.  ,  27.44,  32.93,  28.83,  22.08, 808.  ,  27.44,  32.93,
         28.83,  22.08],
       [809.  ,  28.63,  34.35,  31.03,  22.68, 809.  ,  28.63,  34.35,
         31.03,  22.68],
       [810.  ,  30.35,  36.42

In [ ]:
#2.2 Vertical Stacking
resultarray=np.vstack((d1,d2))
resultarray

array([[   nan,    nan,    nan,    nan,    nan],
       [801.  ,  28.48,  34.18,  30.56,  22.23],
       [802.  ,  28.1 ,  33.72,  30.68,  22.82],
       [803.  ,  26.16,  31.39,  28.2 ,  22.53],
       [804.  ,  26.16,  31.39,  28.78,  20.93],
       [805.  ,  26.1 ,  31.32,  28.22,  20.82],
       [806.  ,  25.45,  30.54,  27.73,  21.05],
       [807.  ,  26.16,  31.39,  28.01,  20.51],
       [808.  ,  27.44,  32.93,  28.83,  22.08],
       [809.  ,  28.63,  34.35,  31.03,  22.68],
       [810.  ,  30.35,  36.42,  31.38,  23.1 ],
       [   nan,    nan,    nan,    nan,    nan],
       [801.  ,  28.48,  34.18,  30.56,  22.23],
       [802.  ,  28.1 ,  33.72,  30.68,  22.82],
       [803.  ,  26.16,  31.39,  28.2 ,  22.53],
       [804.  ,  26.16,  31.39,  28.78,  20.93],
       [805.  ,  26.1 ,  31.32,  28.22,  20.82],
       [806.  ,  25.45,  30.54,  27.73,  21.05],
       [807.  ,  26.16,  31.39,  28.01,  20.51],
       [808.  ,  27.44,  32.93,  28.83,  22.08],
       [809.  ,  28.

In [ ]:
#3.1 Range
nparray=np.arange(0,12,1).reshape(3,4)
nparray

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#3.2 Linearly Separable
nparray=np.linspace(start=0,stop=24,num=12).reshape(3,4)
nparray

array([[ 0.        ,  2.18181818,  4.36363636,  6.54545455],
       [ 8.72727273, 10.90909091, 13.09090909, 15.27272727],
       [17.45454545, 19.63636364, 21.81818182, 24.        ]])

In [ ]:
#3.3 Empty Array
nparray=np.empty((3,3),int)
nparray

array([[           72578848,                   0, 7309940467525749258],
       [   2921541686949236, 7306000154083992352,                  33],
       [           72598864,     139723366243312,                 144]])

In [ ]:
#3.4 Emply like some other array
nparray=np.empty_like(d1)
nparray

array([[nan, nan, nan, nan, nan],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [ ]:
#3.5 Index Matrix
nparray=np.identity(3)
nparray

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#4.1 Arithmatic operation
array1=np.array([1,2,3,4,5])
array2=np.array([11,12,13,14,15])
print(d1)
print(d2)

[[   nan    nan    nan    nan    nan]
 [801.    28.48  34.18  30.56  22.23]
 [802.    28.1   33.72  30.68  22.82]
 [803.    26.16  31.39  28.2   22.53]
 [804.    26.16  31.39  28.78  20.93]
 [805.    26.1   31.32  28.22  20.82]
 [806.    25.45  30.54  27.73  21.05]
 [807.    26.16  31.39  28.01  20.51]
 [808.    27.44  32.93  28.83  22.08]
 [809.    28.63  34.35  31.03  22.68]
 [810.    30.35  36.42  31.38  23.1 ]]
[[   nan    nan    nan    nan    nan]
 [801.    28.48  34.18  30.56  22.23]
 [802.    28.1   33.72  30.68  22.82]
 [803.    26.16  31.39  28.2   22.53]
 [804.    26.16  31.39  28.78  20.93]
 [805.    26.1   31.32  28.22  20.82]
 [806.    25.45  30.54  27.73  21.05]
 [807.    26.16  31.39  28.01  20.51]
 [808.    27.44  32.93  28.83  22.08]
 [809.    28.63  34.35  31.03  22.68]
 [810.    30.35  36.42  31.38  23.1 ]]


In [ ]:
# Addition
print(np.add(d1,d2))
# Subtraction
print(np.subtract(d1,d2))
# Multiplication
print(np.multiply(d1,d2))
# Division
print(np.divide(d1,d2))

[[    nan     nan     nan     nan     nan]
 [1602.     56.96   68.36   61.12   44.46]
 [1604.     56.2    67.44   61.36   45.64]
 [1606.     52.32   62.78   56.4    45.06]
 [1608.     52.32   62.78   57.56   41.86]
 [1610.     52.2    62.64   56.44   41.64]
 [1612.     50.9    61.08   55.46   42.1 ]
 [1614.     52.32   62.78   56.02   41.02]
 [1616.     54.88   65.86   57.66   44.16]
 [1618.     57.26   68.7    62.06   45.36]
 [1620.     60.7    72.84   62.76   46.2 ]]
[[nan nan nan nan nan]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[          nan           nan           nan           nan           nan]
 [6.4160100e+05 8.1111040e+02 1.1682724e+03 9.3391360e+02 4.9417290e+02]
 [6.4320400e+05 7.8961000e+02 1.1370384e+03 9.4126240e+02 5.2075240e+02]
 [6.4480900e+05 6.8434560e+02 9.8533210e+02 7.9524000

In [3]:
# Standard Deviation
print(np.std(d1))
#Minimum
print(np.min(d1))
#Summation
print(np.sum(d1))
#Median
print(np.median(d1))
#Mean
print(np.mean(d1))
#Mode
from scipy import stats
print("Most Frequent element=",stats.mode(d1)[0])
print("Number of Occarances=",stats.mode(d1)[1])
# Variance
print(np.var(d1))



NameError: ignored