In [ ]:
import numpy as np
array1=np.array([[1,2,3],[4,5,6],[7,8,9]])
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array2=np.array([[11,12,13],[14,15,16],[17,18,19]])
array2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [ ]:
#Addition
resultarray=array1+array2
print("\nUsing Operator:\n",resultarray)
resultarray=np.add(array1,array2)
print("\nUsing Numpy Function:\n",resultarray)




Using Operator:
 [[12 14]
 [16 18]]

Using Numpy Function:
 [[12 14]
 [16 18]]


In [ ]:
#Subtraction
resultarray=array1-array2
print("\nUsing Operator:\n",resultarray)
resultarray=np.subtract(array1,array2)
print("\nUsing Numpy Function:\n",resultarray)




Using Operator:
 [[-10 -10]
 [-10 -10]]

Using Numpy Function:
 [[-10 -10]
 [-10 -10]]


In [ ]:
#Multiplication
resultarray=array1*array2
print("\nUsing Operator:\n",resultarray)
resultarray=np.multiply(array1,array2)
print("\nUsing Numpy Function:\n",resultarray)


Using Operator:
 [[11 24]
 [39 56]]

Using Numpy Function:
 [[11 24]
 [39 56]]


In [ ]:
#Division
resultarry=array1/array2
print("\nUsing Operator:\n",resultarray)
resultarray=np.divide(array1,array2)
print("\nUsing Numpy Function:\n",resultarray)


Using Operator:
 [[11 24]
 [39 56]]

Using Numpy Function:
 [[0.09090909 0.16666667]
 [0.23076923 0.28571429]]


In [1]:
#MOD
resultarry=array1%array2
print("\nUsing Operator:\n",resultarray)
resultarray=np.mod(array1,array2)
print("\nUsing Numpy Function:\n",resultarray)

NameError: ignored

In [ ]:
#Dot Product
resultarray=np.dot(array1,array2)
print("",resultarray)

 [[ 90  96 102]
 [216 231 246]
 [342 366 390]]


In [ ]:
#Transpose
resultarray=np.transpose(array1)
print(resultarray)


[[1 3]
 [2 4]]


In [ ]:
#2.1 Horizontal Stacking
resultarray=np.hstack((array1,array2))
resultarray

NameError: ignored

In [ ]:
#2.2 Vertical Stacking
resultarray=np.vstack((array1,array2))
reaultarray

NameError: ignored

In [ ]:
#3.1 Range
nparray=np.arange(0,12,1).reshape(3,4)
nparray

NameError: ignored

In [ ]:
#3.2 Linearly Separable
nparray=np.linspace(start=0,stop=24,num=12).reshape(3,4)
nparray

NameError: ignored

In [ ]:
#3.3 Empty Array
nparray=np.empty((3,3),int)
nparray

NameError: ignored

In [ ]:
#3.4 Emply like some other array
nparray=np.empty_like(array1)
nparray

NameError: ignored

In [ ]:
#3.5 Index Matrix
nparray=np.identity(3)
nparray

NameError: ignored

In [ ]:
#4.1 Arithmatic operation
array1=np.array([1,2,3,4,5])
array2=np.array([11,12,13,14,15])
print(array1)
print(array2)

NameError: ignored

In [ ]:
# Addition
print(np.add(array1,array2))
# Subtraction
print(np.subtract(array1,array2))
# Multiplication
print(np.multiply(array1,array2))
# Division
print(np.divide(array1,array2))

NameError: ignored

In [ ]:
#4.2 Statistical and mathmatical operation
array1=np.array([1,2,3,4,5,9,6,7,8,9,9])
# Standard Deviation
print(np.std(array1))
#Minimum
print(np.min(array1))
#Summation
print(np.sum(array1))
#Median
print(np.median(array1))
#Mean
print(np.mean(array1))
#Mode
from scipy import stats
print("Most Frequent element=",stats.mode(array1)[0])
print("Number of Occarances=",stats.mode(array1)[1])
# Variance
print(np.var(array1))

In [ ]:
#4.3 Bitwise Operator
array1=np.array([1,2,3],dtype=np.uint8)
array2=np.array([4,5,6])
# AND
resultarray=np.bitwise_and(array1,array2)
print(resultarray)
# OR
resultarray=np.bitwise_or(array1,array2)
print(resultarray)
#LeftShift
resultarray=np.left_shift(array1,2)
print(resultarray)
#RightShift
resultarray=np.right_shift(array1,2)
print(resultarray)

In [3]:
print(np.binary_repr(10,8))
resultarray=np.left_shift(10,2)
print(resultarray)
print(np.binary_repr(np.left_shift(10,2),8))


NameError: ignored

In [ ]:
#5.1 Copy
array1=np.arange(1,10)
print(array1)
newarray=array1.copy()
print(newarray)
##modification in Original Array
array1[0]=100
print(array1)
print(newarray)

In [ ]:
#5.2 View
array1=np.arange(1,10)
print(array1)
newarray=array1.view()
print(newarray)
##modification in Original Array
array1[0]=100
print(array1)
print(newarray)

In [2]:
#6 Serching
array1=np.array([[1,2,3,12,5,7],[94,5,6,7,89,44],[7,8,9,11,13,14]])
print(array1)


NameError: ignored

In [ ]:
np.sort(array1,axis=0)#Horizontally Sort

In [ ]:
np.sort(array1,axis=1)# Vertically Sort

In [ ]:
#7 Searching
array1=np.array([1,2,3,12,5,7])
np.searchsorted(array1,7,side="left")#Perform Search After sorting

In [ ]:
#8 Counting
array1=np.array([1,2,3,12,5,7,0])
print(np.count_nonzero(array1))#Return total Non Zero element
print(np.nonzero(array1))#Return Index
print(array1.size)#Total Element

In [ ]:
#9 Data Stacking
array1=np.array(np.arange(1,5).reshape(2,2))
print(array1)
array2=np.array(np.arange(11,15).reshape(2,2))
print(array2)
nwearray=np.stack([array1,array2],axis=0)
print(newarray)
newarray=np.stack([array1,array2],axis=1)
print(newarray)

In [ ]:
#10 Append
array1=np.arange(1,10).reshape(3,3)
print(array1)
array2=np.arange(21,30).reshape(3,3)
print(array2)

In [4]:
np.append(array1,array2,axis=0)


NameError: ignored

In [ ]:
np.append(array1,array2,axis=1)


In [ ]:
#11 Concat
array1=np.arange(1,10).reshape(3,3)
print(array1)
array2=np.arange(21,30).reshape(3,3)
print(array2)